import { downloadBlobFile } from '@/services/fileDownload.js'

const DEMO_ROWS = [
  ['Program', 'Students'],
  ['BSCE', '800'],
  ['BSEE', '450'],
  ['BSME', '600'],
]

function toCsvField(value) {
  const stringValue = String(value ?? '')
  if (!/[",\r\n]/.test(stringValue)) return stringValue
  return `"${stringValue.replace(/"/g, '""')}"`
}

export async function downloadDemoReport(format = 'pdf') {
  const normalizedFormat = String(format || 'pdf').toLowerCase()

  if (normalizedFormat === 'csv') {
    const csvContent = `\uFEFF${DEMO_ROWS.map((row) => row.map(toCsvField).join(',')).join('\r\n')}`
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    return downloadBlobFile(blob, 'aura-enrollment-demo.csv', {
      title: 'Aura enrollment demo',
    })
  }

  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('College of Engineering Overview', 40, 54)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text('Enrollment distribution demo report generated by Aura.', 40, 76)

  let y = 118
  DEMO_ROWS.slice(1).forEach(([program, students]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(program, 40, y)
    doc.setFont('helvetica', 'normal')
    doc.text(`${students} students`, 150, y)
    y += 28
  })

  return downloadBlobFile(doc.output('blob'), 'aura-enrollment-demo.pdf', {
    title: 'Aura enrollment demo',
  })
}
